# Generated by Django 5.2.4 on 2025-12-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='Participant_id',
            new_name='participant_id',
        ),
    ]
