# Generated by Django 5.2.4 on 2025-12-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_rename_participant_id_participant_participant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Participant',
            new_name='participant',
        ),
    ]
